# Generated by Django 3.2.5 on 2022-05-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('field', models.CharField(max_length=80, verbose_name='field of specialization')),
            ],
        ),
        migrations.CreateModel(
            name='RefferalPhysician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('field', models.CharField(max_length=80, verbose_name='field of specialization')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='refferal fee')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='service name')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='service fee')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='invoice code')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='reception date')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient', verbose_name='patient')),
                ('RefferalPhysician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.refferalphysician', verbose_name='refferal physician')),
                ('services', models.ManyToManyField(to='reception.Service')),
            ],
        ),
    ]
