# Generated by Django 3.2.5 on 2022-05-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPhysician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('field', models.CharField(max_length=80, verbose_name='field of specialization')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='referral fee')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='RefferalPhysician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.referralphysician', verbose_name='refferal physician'),
        ),
        migrations.DeleteModel(
            name='RefferalPhysician',
        ),
    ]
