# Generated by Django 3.2.5 on 2022-06-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_auto_20220605_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='ct_income',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='mri_income',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='x_income',
        ),
    ]
