# Generated by Django 4.0.6 on 2022-07-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0011_auto_20220605_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='reception date')),
                ('time', models.TimeField(verbose_name='reception time')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient', verbose_name='patient')),
                ('RefferalPhysician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.referralphysician', verbose_name='refferal physician')),
                ('services_ctscan', models.ManyToManyField(blank=True, related_name='ct_service', to='reception.servicectscan')),
            ],
        ),
        migrations.CreateModel(
            name='Mri_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='reception date')),
                ('time', models.TimeField(verbose_name='reception time')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient', verbose_name='patient')),
                ('RefferalPhysician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.referralphysician', verbose_name='refferal physician')),
                ('services_mri', models.ManyToManyField(blank=True, related_name='mri_services', to='reception.servicemri')),
            ],
        ),
        migrations.CreateModel(
            name='X_Ray_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='reception date')),
                ('time', models.TimeField(verbose_name='reception time')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient', verbose_name='patient')),
                ('RefferalPhysician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.referralphysician', verbose_name='refferal physician')),
                ('services_xray', models.ManyToManyField(blank=True, related_name='x_invoice', to='reception.servicexray')),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
